DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  userName VARCHAR(250) NOT NULL,
  birthDate DATE NOT NULL,
  countryOfResidence VARCHAR(250) NOT NULL,
  phoneNumber VARCHAR(250) DEFAULT NULL,
  gender VARCHAR(250) DEFAULT NULL
);
